# Generated by Django 2.1.1 on 2018-10-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rno',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
