# Generated by Django 2.0.4 on 2018-10-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('topic', models.CharField(max_length=50)),
            ],
        ),
    ]
