# Generated by Django 2.0.4 on 2018-10-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sms', '0002_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
