# Generated by Django 2.0.4 on 2018-10-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sms', '0003_auto_20181009_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateField(),
        ),
    ]
